package.json

Mastarm depends on `postcss-reporter` in `lib/transform.js`. This adds `postcss-reporter` as a
dependency in package.json.
Came across this while working on conveyal/scenario-editor#126

fix(package.json): Add postcss-reporter as dependency

---

bin/mastarm
package.json
tests/bin/mastarm.test.js
tests/mocks/mockComponent.js

I also made a test case to prove that it is needed for static class
properties

Require babel-eslint after all

---

README.md
bin/mastarm
lib/jest-preprocessor.js
lib/test.js
tests/lib/__snapshots__/test.test.js.snap
tests/lib/test.test.js

Add ability to pass along the following Jest cli params:
- patterns to isolate testing to matching files
- setupFiles for global setups to be ran before each test
Add documentation about these features
Remove es2015 preset from Jest preprocessing for faster transformations
(hat tip to https://twitter.com/cpojer/status/783651892320571394)

feat(test): Add various improvements to testing with Jest

---

.npmignore

Since the react folder is included as an entry in the .gitignore file, it is not published to npm.
By making a separate file for npm publishing we can ensure that the folder does get included when publishing to npm.

Add .npmignore file to allow inclusion of react folder

---

__tests__/lib/__snapshots__/util.js.snap
__tests__/lib/util.js

I accidentally updated a snapshot and made a test pass when it should've failed.  Therefore I added hardcoded assertions as well so that we don't 100% rely on snapshots.

Fix snapshot and improve robustness

---

__tests__/lib/__snapshots__/util.js.snap
__tests__/lib/util.js
bin/mastarm
lib/util.js
package.json
yarn.lock

Use `"prestart": "yarn"` in scripts instead.

refactor(dependency-check): Remove dependency checking. 

---

__tests__/lib/__snapshots__/load-config.js.snap
__tests__/lib/__snapshots__/test.js.snap
__tests__/lib/load-config.js
__tests__/lib/test.js
__tests__/lib/util.js
bin/mastarm
lib/js-transform.js
lib/test.js
lib/util.js

As I was setting up the commute settings I was trying to figure out how the settings got read into the project.  In my research I found that the test runner doesn’t read in all these settings properly.  I made this fix so that it will have the same environment setup as all js builds do.

Improve environment settings in test runs

---

__tests__/bin/mastarm.js
lib/build.js
lib/css-transform.js

* accesses the [log](https://github.com/substack/watchify#bonlog-function-msg-) event emitted by watchify
* writes whenever a css file has been written

Add console.log output during builds

---

lib/eslintrc.json
package.json
yarn.lock

See https://github.com/evcohen/eslint-plugin-jsx-a11y for more info.
This adds ~65 warnings to Analysis UI and ~58 to the Data Tools UI.

Add eslint plugin for jsx-a11y checking

---

lib/push-to-s3.js

s3 upload was failing when passing in a readable stream created by browserify. It would begin the upload but eventually fail. Separating out the process to build, then upload fixes this problem and allows us to publish the filesize.

Build, then deploy to fix timeout errors with s3 upload

---

lib/logger.js
lib/push-to-s3.js
package.json
yarn.lock

We have really nice emoji in slack for deploy logging, but the CLI was hard to read due to the links
and the spelled-out emoji. Now links are removed and emoji displayed on the command line when
deploying.
Before:
After:

feat(logging): Display emoji on command line :tada:

---

__tests__/lib/__snapshots__/build.js.snap
__tests__/lib/push-to-s3.js
lib/browserify.js
lib/build.js
lib/css-transform.js
lib/js-build.js
lib/notify-slack.js
lib/push-to-s3.js

Source maps were not being extracted from the built JavaScript files during deployment. This fixes that and automates their upload.

Extract source maps from JavaScript on deploy

---

__tests__/lib/__snapshots__/jest.js.snap
__tests__/lib/jest.js
bin/mastarm-test
lib/jest.js

The current cacheDirectory is set to `tmp` within master’s jest config. This creates the directory `tmp` in the project directory which typically needs to be ignored in a .gitignore file.  The default directory is /tmp I think.  I think the only reason I was using the tmp directory initially was when I was testing out jest, but now it’s not needed and causes a headache each time a new project is started.
The forceExit argument sometimes surpasses console.log statements, so I made it optional.  This Jest docs note that this feature is a crutch for not properly tearing down tests:  https://facebook.github.io/jest/docs/cli.html#forceexit

Use default directory for jest caches

---

.travis.yml
__tests__/lib/__snapshots__/build.js.snap
package.json

Node 8 comes with a host of features and will be their LTE soon. Switching over will cause a breaking change as we don't want our libraries to have mismatched versions.

Update node engine to 8 and npm to 5

---

package.json
yarn.lock

The semantic-release deployment script is misconfigured and the last Travis build on master didn't produce a new release.  This should fix that.

Update to latest semantic-release

---

lib/eslintrc.json

This will help better organize flow type definitions.  This particular rule also comes with a fix option that makes it super easy to maintain compliance.

Add new error rule for sorting flowtype definitions

---

lib/js-transform.js

These environment variables can be used in our react projects to show useful information in the app.  Here is a proof-of-concept in the footer of datatools:

Add some useful environment variables

---

lib/babel-config.js

Since we are already using babel-env we can use the `useBuiltIns` flag to include the required transform runtime. See bable-env docs for more info: https://babeljs.io/docs/en/babel-preset-env#usebuiltins

Use babel-env more appropriately

---

bin/mastarm-build
lib/babel-config.js
lib/browserify.js
lib/budo.js
lib/build.js
lib/js-build.js
lib/js-transform.js
package.json
yarn.lock

This adds the option to instrument code during browserify js builds.  This works in conjunction with the e2e tests performed in datatools-ui.

Allow instrumentation of js code

---

README.md

Automated dependency bumps for security in #264, #265, and #266 will not trigger a semver release.
I'm using this wording tweak in README to handle this.

Trigger patch/micro release with README tweak

---

package.json
yarn.lock

0.85.0 introduces a host of new flow type issues in Data Tools. This is explained in this blog post:
https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8
re ibi-group/datatools-ui#442

Downgrade flow to 0.84.0

---

README.md
package.json
yarn.lock

Patch release to downgrade flow to 0.84.0 (to resolve Data Tools flow typing issues #269).

Patch release: Flow downgrade

---

README.md
bin/mastarm-test
lib/jest.js

This change allows for the output of a test run to a specified json file.

Allow passthrough of any jest CLI arguments

---

yarn.lock

A travis build failed due to a [warning encountered](https://travis-ci.org/conveyal/mastarm/builds/565644464#L534) during `yarn cover`. This upgrades mastarm's deps to fix this warning/test.

Upgrade deps to resolve caniuse-lite build warning

---

README.md
bin/mastarm-deploy
lib/logger.js

Adds the ability to log deployments to MS Teams. Configure an incoming webhook in MS Teams (or use an existing one) and then add it to the env.yml file that is being used during the build to deploy.

Log deployments to MS Teams

---

README.md
bin/mastarm-deploy
package.json
yarn.lock

This makes it possible to use the deploy command to merely upload files in a directory to s3 and invalidate the cloudfront entries for each file without building with browserify.

Allow deployment of just static files

---

lib/eslintrc.json

**Important note: This PR is for merging directly to master!**
Why is this a PR directly to master? Because #295 upgraded a whole bunch of eslint packages to new major versions which introduced thousands of (in my opinion good) linting errors that will eventually make our code more standardized. When we eventually merge `dev` to master to create the next master release we should bump it up to another major version to reflect this change.
As asked in https://github.com/ibi-group/datatools-ui/pull/508, I went ahead and updated the code to pass all the jsx/a11y tests. However, [a certain case of the `label-has-associated-control` rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md#case-my-label-and-input-components-are-custom-componen …

Disable nesting checks for jsx-a11y/label-has-for
